[tool.ruff]
# Target the ApexDAG and tests directories
src = ["ApexDAG", "tests"]
line-length = 88
indent-width = 4

exclude = [
    ".git",
    ".ruff_cache",
    "__pypackages__",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B"]

ignore = ["ARG001", "ARG002"]

[tool.ruff.format]
quote-style = "double"
