NODE_TYPES = {
    "VARIABLE": 0,
    "IMPORT": 1,
    "LITERAL": 2,
    "FUNCTION": 3,
    "INTERMEDIATE": 4,
    "IF": 5,
    "LOOP": 6,
    "CLASS": 7,
}

EDGE_TYPES = {
    "CALLER": 0,
    "INPUT": 1,
    "OMITTED": 2,
    "BRANCH": 3,
    "LOOP": 4,
    "FUNCTION_CALL": 5,
}

DOMAIN_EDGE_TYPES = {
    "MODEL_TRAIN": 0,
    "MODEL_EVALUATION": 0,
    "HYPERPARAMETER_TUNING": 0,
    "DATA_EXPORT": 4,
    "DATA_IMPORT_EXTRACTION": 1,
    "DATA_TRANSFORM": 2,
    "EDA": 3,
    "ENVIRONMENT": 4,
    "NOT_INTERESTING": 4
}

DOMAIN_EDGE_TYPES_SUBSET_MAPING = {
    "MODEL_TRAIN": "MODEL_TRAIN",
    "MODEL_EVALUATION": "MODEL_TRAIN",
    "HYPERPARAMETER_TUNING": "MODEL_TRAIN",
    "DATA_EXPORT": "NOT_INTERESTING",
    "DATA_IMPORT_EXTRACTION": "DATA_IMPORT_EXTRACTION",
    "DATA_TRANSFORM": "DATA_TRANSFORM",
    "EDA": "EDA",
    "ENVIRONMENT": "NOT_INTERESTING",
    "NOT_INTERESTING": "NOT_INTERESTING",
}

VERBOSE = False

REVERSE_NODE_TYPES = {v: k for k, v in NODE_TYPES.items()}
REVERSE_EDGE_TYPES = {v: k for k, v in EDGE_TYPES.items()}
