model_name: "gemini-3.1-flash-lite"
max_tokens: 100000000
max_rpm: 3000
max_depth: 3
llm_provider: "google"
retry_attempts: 5
retry_delay: 60
success_delay: 0
sleep_interval: 0
max_workers: 5
use_refiner: false
